# OCD HITS: EVERYTHING SORTED IN ALPHABETICAL ORDER!

# Sources
tap 'buo/cask-upgrade'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'd12frosted/emacs-plus'
tap 'homebrew/bundle'
tap 'homebrew/core'

# Utilities
brew 'aspell'
brew 'd12frosted/emacs-plus/emacs-plus'
brew 'git'
brew 'htop'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Apps from "Web"
# cask 'firefox'
# cask 'franz'
cask 'iterm2-nightly'
# cask 'slack'
cask 'spectacle'
# cask 'spotify'
# cask 'vlc'
